warning_threshold: 100 # allow max 100 warnings, then show error

excluded: # paths to ignore during linting.
  - Pods
  - Carthage
  - Geomobile-users/SwiftGen
  - Geomobile-usersTests/**/*.generated.swift

disabled_rules:
  - line_length
  - trailing_whitespace
  - statement_position
  - force_cast
  - vertical_whitespace
  - redundant_string_enum_value
  - unused_closure_parameter
  - nesting
  - identifier_name
  - large_tuple
  - force_try
  - trailing_comma

#rule parameters
type_name:
  max_length:
    warning: 50
    error: 60
type_body_length:
  warning: 350
  error: 600
